version: "3.5"

services: 
    node: 
        container_name: "Next_Shop_Proj"
        build:
            context: .
            dockerfile: ./docker/node.prod.Dockerfile
        restart: "always"
        working_dir: /shop
        ports: 
            - 8081:3000
        command: npm start
